/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sams.view;
import com.sams.dao.StudentDAO;
import com.sams.dao.CourseDAO;
import com.sams.model.Student;
import com.sams.model.Course;
import java.util.List;

/**
 *
 * @author supun
 */
public class EnrollmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnrollmentForm.class.getName());

    private void initComboBoxes() {
        
        // 1. ශිෂ්‍යයන් Load කිරීම
        com.sams.dao.StudentDAO sDao = new com.sams.dao.StudentDAO();
        java.util.List<com.sams.model.Student> students = sDao.getAllStudents();
        
        cmbStudent.removeAllItems(); // පරණ ඒව අයින් කරන්න
        for (com.sams.model.Student s : students) {
            // මෙතනදී පේන්නේ නම විතරයි, නමුත් object එකක් විදිහට තමයි තියෙන්නේ
            cmbStudent.addItem(s.getStudentName()); 
        }

        // 2. පාඨමාලා Load කිරීම
        com.sams.dao.CourseDAO cDao = new com.sams.dao.CourseDAO();
        java.util.List<com.sams.model.Course> courses = cDao.getAllCourses();
        
        cmbCourse.removeAllItems(); // පරණ ඒව අයින් කරන්න
        for (com.sams.model.Course c : courses) {
            cmbCourse.addItem(c.getCourseName());
        }
    }
    private void loadEnrollments() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblEnrollment.getModel();
        model.setRowCount(0); 

        com.sams.dao.EnrollmentDAO dao = new com.sams.dao.EnrollmentDAO();
        java.util.List<com.sams.model.Enrollment> list = dao.getAllEnrollments();

        for (com.sams.model.Enrollment e : list) {
            model.addRow(new Object[]{e.getId(), e.getStudentName(), e.getCourseName(), e.getEnrollmentDate()});
        }
    }
    
    /**
     * Creates new form EnrollmentForm
     */
    public EnrollmentForm() {
        initComponents();
        initComboBoxes();
        loadEnrollments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbStudent = new javax.swing.JComboBox<>();
        cmbCourse = new javax.swing.JComboBox<>();
        btnEnroll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrollment = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudent.addActionListener(this::cmbStudentActionPerformed);

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCourse.addActionListener(this::cmbCourseActionPerformed);

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(this::btnEnrollActionPerformed);

        tblEnrollment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEnrollment);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnroll)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cmbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnEnroll)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnDelete)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStudentActionPerformed

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
       
      String sName = cmbStudent.getSelectedItem().toString();
    String cName = cmbCourse.getSelectedItem().toString();

    // 1. DAO හරහා ID එක ලබා ගැනීම
    int sId = new com.sams.dao.StudentDAO().getStudentIdByName(sName);
    int cId = new com.sams.dao.CourseDAO().getCourseIdByName(cName);

    // ID එක 0 නම් Database එකේ නම නැත
    if(sId == 0 || cId == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Student or Course not found in database!");
        return;
    }

    // 2. Enrollment Object එකක් හදන්න
    com.sams.model.Enrollment enrollment = new com.sams.model.Enrollment();
    enrollment.setStudentId(sId);
    enrollment.setCourseId(cId);
    enrollment.setEnrollmentDate(new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));

    // 3. Service එක හරහා Save කරන්න
    com.sams.service.EnrollmentService service = new com.sams.service.EnrollmentService();
    boolean success = service.enrollStudent(enrollment); 

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Student Enrolled Successfully!");
        loadEnrollments(); // Table එක Refresh කරන්න
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error in Enrolling! (Check Database)");
    }  
        
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblEnrollment.getSelectedRow();

    // 2. කිසිවක් තෝරා නැත්නම් Error පණිවිඩයක් දීම
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "කරුණාකර ඉවත් කිරීමට අවශ්‍ය පේළියක් Table එකෙන් තෝරන්න!");
        return;
    }

  
    int id = Integer.parseInt(tblEnrollment.getValueAt(selectedRow, 0).toString());

    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "ඔබට මෙම Enrollment වාර්තාව මකාදැමීමට අවශ්‍යද?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
   
        com.sams.dao.EnrollmentDAO dao = new com.sams.dao.EnrollmentDAO();
        if (dao.deleteEnrollment(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "සාර්ථකව මකාදමන ලදී!");
            // 6. Table එක නැවත Refresh කිරීම
            loadEnrollments(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "මකාදැමීමේ දෝෂයක් සිදුවිය!");
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnrollmentForm().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnrollment;
    // End of variables declaration//GEN-END:variables




// EnrollmentForm class එකේ අන්තිම } වරහනට උඩින් මෙය දාන්න
    class ComboBoxItem {
        int id;
        String name;

        public ComboBoxItem(int id, String name) {
            this.id = id;
            this.name = name;
        }

        @Override
        public String toString() {
            return name; // ComboBox එකේ නම පෙන්වීමට
        }
    }
}




